### ISSUE TITLE
[1pt] Create MusicAlbum class in a separate .rb file

### ISSUE THREAD

**Issue by sarazaToussaint** [sarazaToussaint/Ruby-capstone#17]
- All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.
- can_be_archived?() in the MusicAlbum class
should override the method from the parent class
should return true if the parent's method returns true AND if on_spotify equals true
otherwise, it should return false

**Comment by ibr5500** [comment]
We have done it
